# Site settings
title: Concentration in Leadership and Negotiation
email: edwardf@mit.edu
description: tbd
baseurl: "/"
url: "http://lead.mit.edu"

# Build settings
markdown: kramdown

sass:
  style: compressed
